---
title: C6320 |Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: f07ca6bdc7300a4029caf272c80d752997884d68
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 08/22/2018
ms.locfileid: "47481902"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

本主题的最新版本，请参阅[C6320](https://docs.microsoft.com/visualstudio/code-quality/c6320)。  
  
警告 C6320： 异常筛选器表达式为常数 EXCEPTION_EXECUTE_HANDLER。 这可能会屏蔽不打算处理的异常  
  
 此警告意味着使用 EXCEPTION_EXECUTE_HANDLER 常量在 __except 块的副作用。 在此情况下中的语句\_的 _except 块将始终执行来处理异常，包括您不希望在特定的函数中处理的异常。 建议您检查之前处理该异常。  
  
## <a name="example"></a>示例  
 下面的代码生成此警告，因为 __except 块就用来处理所有类型的异常：  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 若要更正此警告，请使用`GetExceptionCode`检查特定异常之前处理它，如下面的代码中所示：  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>请参阅  
 [try-except 语句](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



